<a href="https://colab.research.google.com/github/CaptMadhan/AICTE-DailyWageWorkers-App/blob/master/Bus_Depot_Allocation_project_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **North-West Rule to find IBFS**

In [17]:
import numpy as np
import sys
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

In [18]:
def northWestIBFS(fact, ware,weights):
  n = 0
  w = 0
  ibfs = 0
  arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))])  
  while  n < len(fact) and w < len(ware):
    if fact[n] > ware[w]:
      arr[n][w] = ware[w]
      fact[n] -= ware[w]
      ware[w] = 0
      w += 1
    elif fact[n] < ware[w]:
      arr[n][w] = fact[n]
      ware[w] -= fact[n]
      fact[n] = 0
      n += 1
    else:
      arr[n][w] = fact[n]
      fact[n] = 0
      ware[w] = 0
      n += 1
      w += 1
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      ibfs += arr[i][j] * weights[i][j]
  return arr,ibfs


In [19]:
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

northWestIBFS(fact, ware,weights)

(array([[ 5,  2,  0,  0],
        [ 0,  6,  3,  0],
        [ 0,  0,  4, 14]]), 1015)

In [20]:
fact = [30,70,50]
ware = [40,30,40,40]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

northWestIBFS(fact, ware,weights)

(array([[30,  0,  0,  0],
        [10, 30, 30,  0],
        [ 0,  0, 10, 40]]), 4870)

In [21]:
fact = [10,35,25]
ware = [20,25,25]
weights = np.array([[2,3,1],
                    [5,4,8],
                    [5,6,8]])

northWestIBFS(fact, ware,weights)

(array([[10,  0,  0],
        [10, 25,  0],
        [ 0,  0, 25]]), 370)

In [22]:
fact = [70,
        30,
        50]
ware = [65,42,43]
weights = np.array([[5,7,8],
                    [4,4,6],
                    [6,7,7]])

northWestIBFS(fact, ware,weights)

(array([[65,  5,  0],
        [ 0, 30,  0],
        [ 0,  7, 43]]), 830)

# **Row-Minima method**

In [23]:
def row_MinimaIBFS(fact, ware, weights):
  n = 0
  w = 0
  ibfs = 0
  arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))]) 
  while  n < len(fact) and w < len(ware):
    if max(ware) > fact[n]:
      w = ware.index(max(ware))
      arr[n][w] = fact[n]
      ware[w] -= fact[n]
      fact[n] = 0
      n += 1
    elif max(ware) < fact[n]:
      w = ware.index(max(ware))
      arr[n][w] = ware[w]
      fact[n] -= ware[w]
      ware[w] = 0
    else:
      w = ware.index(max(ware))
      arr[n][w] = max(ware)
      fact[n] = 0
      ware[w] = 0
      n += 1
      w + 1
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      ibfs += arr[i][j] * weights[i][j]
  return arr,ibfs
      

          

In [24]:

fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

row_MinimaIBFS(fact, ware,weights)

(array([[0, 0, 0, 7],
        [0, 8, 1, 0],
        [5, 0, 6, 7]]), 1110)

In [25]:
fact = [70,
        30,
        50]
ware = [65,42,43]
weights = np.array([[5,7,8],
                    [4,4,6],
                    [6,7,7]])

row_MinimaIBFS(fact, ware,weights)

(array([[65,  0,  5],
        [ 0, 30,  0],
        [ 0, 12, 38]]), 835)

# **Least Cost Method to find IBFS**

In [26]:
weights = np.array([[5,7,8],
                    [5,4,6],
                    [6,2,7]])
np.argwhere(weights == np.min(weights))[0][0]

2

In [27]:
def leastCostIBFS(fact, ware,weights):
  n = 0
  w = 0
  ibfs = 0
  temp_weights = weights.copy()
  arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))]) 
  while sum(fact) > 0:
    n = np.argwhere(weights == np.min(weights))[0][0]
    w = np.argwhere(weights == np.min(weights))[0][1]
    if fact[n] > ware[w]:
      arr[n][w] = ware[w]
      fact[n] -= ware[w]
      ware[w] = 0
    elif fact[n] < ware[w]:
      arr[n][w] = fact[n]
      ware[w] -= fact[n]
      fact[n] = 0
    else:
      arr[n][w] = fact[n]
      fact[n] = 0
      ware[w] = 0
    weights[n][w] = sys.maxsize
  for i in range(len(arr)):
    for j in range(len(arr[0])):
      ibfs += arr[i][j] * temp_weights[i][j]
  return arr,ibfs

In [28]:
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])

leastCostIBFS(fact, ware,weights)

(array([[0, 0, 0, 7],
        [2, 0, 7, 0],
        [3, 8, 0, 7]]), 814)

In [29]:
fact = [70,
        30,
        50]
ware = [65,42,43]
weights = np.array([[5,7,8],
                    [4,4,6],
                    [6,7,7]])

leastCostIBFS(fact, ware,weights)

(array([[35, 35,  0],
        [30,  0,  0],
        [ 0,  7, 43]]), 890)

# VAM

In [30]:
#MAIN
import numpy as np
def leastMinus2ndLeast(lst):
  lst = list(set(lst))
  if len(lst) == 1:
    return lst[0]
  min1 = min(lst)
  lst.remove(min1)
  min2 = min(lst)
  return abs(min2-min1)

def getPenalties(weights, bool_table, nrow, ncol):
  lst_row = []
  lst_col = []
  #Row Penalties
  for i in range(nrow):
    temp = []
    for j in range(ncol):
      if bool_table[i][j] == True:
        temp.append(weights[i][j])
    if len(temp) != 0:
      lst_row.append(leastMinus2ndLeast(temp))

  #Column Penalties
  for i in range(ncol):
    temp = []
    for j in range(nrow):
      if bool_table[j][i] == True:
        temp.append(weights[j][i])
    if len(temp) != 0:
      lst_col.append(leastMinus2ndLeast(temp))
  return lst_row, lst_col

def allocateValue(weights, r, c, result_arr, bool_table, fact, ware, nrow, ncol):
  if fact[r] > ware[c]:
    result_arr[r][c] = ware[c]
    fact[r] -= ware[c]
    ware[c] = 0
    for i in range(nrow):
      bool_table[i][c] = False
  elif fact[r] < ware[c]:
    result_arr[r][c] = fact[r]
    ware[c] -= fact[r]
    fact[r] = 0
    for i in range(ncol):
      bool_table[r][i] = False
  else:
    result_arr[r][c] = fact[r]
    fact[r] = 0
    ware[c] = 0
    for i in range(nrow):
      bool_table[i][c] = False
    for i in range(ncol):
      bool_table[r][i] = False
  return result_arr, bool_table, fact, ware

def VAM(fact, ware, weights):
  nrow = len(fact)
  ncol = len(ware)
  r = 0
  c = 0
  result_arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))])  
  bool_table = np.array([[True for i in range(ncol)] for i in range(nrow)])
  ooo=0
  while ooo != 10 :
    print('*'*20)
    print(bool_table)
    ooo += 1
    penalty_row, penalty_col = getPenalties(weights, bool_table, nrow, ncol)
    max_p_r = max(penalty_row)
    max_p_c = max(penalty_col)
    #print(penalty_row)
    #print(penalty_col)
    if max(max_p_r,max_p_c) == max_p_c:
      c = penalty_col.index(max_p_c)
      temp_lst = []
      for i in range(nrow):
        temp_lst.append(weights[i][c])
      #print(temp_lst)
      min_cost_row_index = temp_lst.index(min(temp_lst))
      result_arr, bool_table, fact, ware = allocateValue(weights, min_cost_row_index, c,result_arr, bool_table, fact, ware, nrow, ncol)
    else:
      r = penalty_row.index(max_p_r)
      temp_lst = []
      for i in range(ncol):
        temp_lst.append(weights[r][i])
      #print(temp_lst)
      min_cost_col_index = temp_lst.index(min(temp_lst))
      result_arr, bool_table, fact, ware = allocateValue(weights, r, min_cost_col_index,result_arr, bool_table, fact, ware, nrow, ncol)
    print(result_arr)
  return result_arr

In [31]:
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])
nrow = len(fact)
ncol = len(ware)
bool_table = np.array([[True for i in range(ncol)] for i in range(nrow)])
result_arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))])  
VAM(fact, ware, weights)

********************
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[0 0 0 0]
 [0 0 0 0]
 [0 8 0 0]]
********************
[[ True False  True  True]
 [ True False  True  True]
 [ True False  True  True]]
[[5 0 0 0]
 [0 0 0 0]
 [0 8 0 0]]
********************
[[False False  True  True]
 [False False  True  True]
 [False False  True  True]]
[[5 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
********************
[[False False  True  True]
 [False False  True  True]
 [False False  True  True]]
[[5 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
********************
[[False False  True  True]
 [False False  True  True]
 [False False  True  True]]
[[5 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
********************
[[False False  True  True]
 [False False  True  True]
 [False False  True  True]]
[[5 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
********************
[[False False  True  True]
 [False False  True  True]
 [False False  True  True]]
[[5 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
********************
[[False False  True 

array([[5, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
fact = [7,9,18]
ware = [5,8,7,14]
weights = np.array([[19,30,50,10],
                    [70,30,40,60],
                    [40,8,70,20]])
nrow = len(fact)
ncol = len(ware)
bool_table = np.array([[True for i in range(ncol)] for i in range(nrow)])
result_arr = np.array([[0 for i in range(len(ware))] for i in range(len(fact))])  

penalty_row, penalty_col = getPenalties(weights, bool_table, nrow, ncol)
max_p_r = max(penalty_row)
max_p_c = max(penalty_col)
#print(penalty_row)
#print(penalty_col)
if max(max_p_r,max_p_c) == max_p_c:
  c = penalty_col.index(max_p_c)
  temp_lst = []
  for i in range(nrow):
    temp_lst.append(weights[i][c])
  #print(temp_lst)
  min_cost_row_index = temp_lst.index(min(temp_lst))
  allocateValue(weights, min_cost_row_index, c)
else:
  r = penalty_col.index(max_p_r)
  temp_lst = []
  for i in range(ncol):
    temp_lst.append(weights[r][i])
  #print(temp_lst)
  min_cost_col_index = temp_lst.index(min(temp_lst))
  allocateValue(weights, r, min_cost_col_index)
print(result_arr)

TypeError: ignored

In [ ]:
def allocateValue(weights, r, c):
  global fact, ware, bool_table, result_arr
  if fact[r] > ware[c]:
    result_arr[r][c] = ware[c]
    fact[r] -= ware[c]
    ware[c] = 0
    for i in range(nrow):
      bool_table[i][c] = False
  elif fact[r] < ware[c]:
    result_arr[r][c] = fact[r]
    ware[c] -= fact[r]
    fact[c] = 0
    for i in range(ncol):
      bool_table[r][i] = False
  else:
    result_arr[r][c] = fact[r]
    fact[r] = 0
    ware[c] = 0
    for i in range(nrow):
      bool_table[i][c] = False
    for i in range(ncol):
      bool_table[r][i] = False

In [33]:
import pandas as pd, numpy as np
data = pd.read_excel('/content/data.xlsx', header=None)
data

0   1   2   3   4
0   0   5   8   7  14
1   7  19  30  50  10
2   9  70  30  40  60
3  18  40   8  70  20

In [45]:
ware = list(data.iloc[0,:])
ware = ware[1:]
ware

[5, 8, 7, 14]

In [46]:
fact = list(data.iloc[:,0])
fact = fact[1:]
fact

[7, 9, 18]

In [47]:
weights = np.array(data.iloc[1:,1:])
weights

array([[19, 30, 50, 10],
       [70, 30, 40, 60],
       [40,  8, 70, 20]])

In [48]:
northWestIBFS(fact,ware, weights)

(array([[ 5,  2,  0,  0],
        [ 0,  6,  3,  0],
        [ 0,  0,  4, 14]]), 1015)